spring.application.name=grievance
server.port=8083

# Uses the variable 'DB_URL' if it exists, otherwise defaults to localhost
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/grievance_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}

# Uses the variable 'DB_USER' if it exists, otherwise defaults to root
spring.datasource.username=${DB_USER:root}

# Uses the variable 'DB_PASS' if it exists, otherwise defaults to your password (or leave blank)
spring.datasource.password=${DB_PASS:Mpsedsn*2809}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
